# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u0FS9Ul66IMZvCqpgRMD-5YvwRVA3vsa
"""

#to remove all the occurenece of an elemnt in a list
li=[1,2,3,3,4]
print(li)
list(filter(lambda a:a!=3,li))