# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u0FS9Ul66IMZvCqpgRMD-5YvwRVA3vsa
"""

#PROJECT :OTP
import random
import string
length= 6
otp= ''
characters = string.ascii_letters+ string.digits
for i in range(length):
  otp = otp + random.choice(characters)
print('OTP',otp)